# This is a render.yaml file.
# It is a blueprint for deploying your application on Render.
# It's like docker-compose.yml, but for the cloud.
#
# services: defines your backend and frontend.
# databases: defines your PostgreSQL database.
services:
  # --- Backend Service ---
  - type: web
    name: omnilearn-backend
    # Use 'docker' since we are deploying a Docker container.
    runtime: docker
    # Path to the backend's Dockerfile
    dockerfilePath: ./backend/Dockerfile
    # Define the public environment variables.
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: omnilearn-db # Must match the database name below
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.4
  # --- Frontend Service ---
  - type: web
    name: omnilearn-frontend
    runtime: docker
    # Path to the frontend's Dockerfile
    dockerfilePath: ./Dockerfile.frontend
    envVars:
      - key: VITE_API_BASE_URL
        value: http://omnilearn-backend:5000
databases:
  # --- PostgreSQL Database ---
  - name: omnilearn-db
    # Use 'postgres' as the database engine.
    databaseName: omnilearn_db # Name of the actual database
    user: omnilearn_user # Username for the database
    plan: free # Use the free tier