"""Add user profile fields and notification preferences

Revision ID: b3eff07dc1da
Revises: f045f0c25b39
Create Date: 2025-07-11 11:46:26.428812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3eff07dc1da'
down_revision = 'f045f0c25b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('notification_preferences', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notification_preferences')
        batch_op.drop_column('avatar')
        batch_op.drop_column('bio')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
