"""Add source type and url to document

Revision ID: f7764ee35eda
Revises: c2008867742d
Create Date: 2025-07-11 14:42:54.150716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7764ee35eda'
down_revision = 'c2008867742d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_type', sa.String(length=50), nullable=False, server_default='pdf'))
        batch_op.add_column(sa.Column('source_url', sa.String(length=500), nullable=True))
        batch_op.alter_column('filepath',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('filepath',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.drop_column('source_url')
        batch_op.drop_column('source_type')

    # ### end Alembic commands ###
